i18n:
  input:
    - /Users/franzi/Workspace/artifacts_stringExtractor/directory_cloudflare/
  report:
    - /Users/franzi/Workspace/artifacts_stringExtractor/report_cloudflare
  exclude:
    - /Users/franzi/Workspace/artifacts_stringExtractor/
  keys:
    html:
      - KEY-geil!!!
    js:
      - ${KEYrambazamba}
    json:
      - thisistheKEY
  localization:
    existing:
      - /Users/franzi/Workspace/artifacts_stringExtractor/localization_files
    export:
      - JSON