qordoba:
  access_token: deda977b-bd69-481d-8f4b-1add19f2272a
  organization_id: 3144
  project_id: 5478
  push:
    sources:
      - '/Users/franzi/Desktop/1_DEMO/Postmates/test_new.json'
  pull:
    targets:
      - '/Users/franzi/Desktop/1_DEMO/Postmates/<filename>.<extension>'